ghs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ghsapp.urls')),
] + static(settings.STATIC_URL,
           document_root=settings.STATIC_ROOT)

ghsapp/models.py
from django.db import models
from django.contrib.auth.models import User


GENDER_CHOICES = [
        ('M', "Male"),
        ('F', "Female"),
]

YES_NO_CHOICES = [
        ('Y', "Yes"),
        ('N', "No"),
]

class userInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile_number = models.CharField(max_length=12)
    profile_pic = models.ImageField(
        upload_to='static/photos/', default='photos/default.png', null=True, blank=True)
    dob = models.CharField(max_length=10)
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES)

    def __str__(self):
        return self.user.username


class doctorInfo(models.Model):

    

    DEGREE_CHOICES = [
        ("MBBS", "Bachelor of Medicine, Bachelor of Surgery(MBBS)"),
        ("BDS", "Bachelor of Dental Surgery(BDS)"),
        ("BAMS", "Bachelor of Ayurvedic Medicine and Surgery(BAMS)"),
        ("BUMS", "Bachelor of Unani Medicine and Surgery(BUMS)"),
        ("BHMS", "Bachelor of Homeopathy Medicine and Surgery(BHMS)"),
        ("BYNS", "Bachelor of Yoga and Naturopathy Sciences(BYNS)"),
        ("B.V.Sc & AH", "Bachelor of Veterinary Sciences and Animal Husbandry(BVSc&AH)"),
        ("MD", "Doctor of Medicine(MD)"),
        ("MS", "Master of Surgery(MS)"),
        ("DM", "Doctorate of Medicine(DM)"),
    ]

    SPECIALITIES_CHOICES = [
        ("ENT", "Ear, Nose and Throat"),
        ("GS", "General Surgery"),
        ("OP", "Ophthalmology"),
        ("OR", "Orthopaedics"),
        ("OAG", "Obstetrics and Gynaecology"),
        ("DVL", "Dermatology, Venerology and Leprosy"),
        ("AST", "Anaesthesiology"),
        ("PSY", "Psychiatry"),
        ("PTH", "Pathology"),
        ("SVD", "Skin and Venereal diseases"),
        ("PHRM", "Pharmacology"),
        ("PMR", "Physical Medicine and Rehabilitation"),
        ("PHY", "Physiology"),
        ("CRD", "Cardiology"),
        ("PDT", "Paediatrics"),
    ]

    doctor = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile_number = models.CharField(max_length=12)
    profile_pic = models.ImageField(
        upload_to='static/photos/', default='photos/default.png', null=True, blank=True)
    hospital_name = models.CharField(max_length=70, blank=True)
    degree_type = models.CharField(max_length=50, choices=DEGREE_CHOICES)
    specialities_type = models.CharField(
        max_length=50, choices=SPECIALITIES_CHOICES)
    dob = models.CharField(max_length=10)
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES)

    def __str__(self):
        return self.doctor.username


class History(models.Model):
    doctor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='doctor')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user')
    date = models.DateField(auto_now=True)
    disease = models.CharField(max_length=200)
    medicine = models.TextField()
    charges = models.PositiveIntegerField()
    hospital_name = models.CharField(max_length=70, blank=True)

    def __str__(self):
        return "{} has detected {} of {}".format(self.doctor.username, self.disease, self.user.username)


class Appointment(models.Model):
    doctor_app = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='doctor_app')
    user_app = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_app')
    date = models.CharField(max_length=10)
    time = models.CharField(max_length=10)

    def __str__(self):
        return "{} has appointmant of {} on {} at {}".format(self.user_app.username, self.doctor_app.username, self.date, self.time)

class Feedback(models.Model):

    doctor_feed = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='doctor_feed')
    user_feed = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_feed')
    waiting_time = models.CharField(max_length=1, choices=YES_NO_CHOICES)
    recommendation = models.CharField(max_length=1, choices=YES_NO_CHOICES)
    feedback = models.TextField(blank=True)

templates/error.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="static/assets/img/Main_LOGO.png" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous" />

    <title>Error Login</title>
</head>

<body>
    <h1 class="text-center">Error</h1>

    <h2 class="text-center">
        This page is only visible to the Employers/Job Posters. To view this page please Register or Login Yourself!
    </h2>

    <div class="text-center">
        <a href="{% url 'signup_user' %}">
            <div class="button">
                <div class="green">Signup User</div>
            </div>
        </a>
        <a href="{% url 'index' %}">
            <div class="button">
                <div class="green">Signup Doctor</div>
            </div>
        </a>
        <a href="{% url 'signin' %}">
            <div class="button">
                <div class="blue">LOGIN</div>
            </div>
        </a>
    </div>

    <style>
        .text-center {
            border: 3px solid #fff;
            padding: 10px;
            margin: 20px;
        }
        
        .button {
            background: linear-gradient(to bottom, #339cff 5%, #0c6de3 100%);
            background-color: #339cff;
            border-radius: 11px;
            border: 3px solid #51a3f5;
            display: inline-block;
            cursor: pointer;
            color: #ffffff;
            font-family: Trebuchet MS;
            font-size: 28px;
            font-weight: bold;
            padding: 7px 76px;
            text-decoration: none;
            text-shadow: 2px 2px 0px #2b82d9;
            margin: 50px;
        }
        
        .button:hover {
            background: linear-gradient(to bottom, #0c6de3 5%, #339cff 100%);
            background-color: #0c6de3;
        }
        
        .button:active {
            position: relative;
            top: 1px;
        }
    </style>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->
    <link rel="icon" href="static/assets/img/Main_LOGO.png" type="image/x-icon">
    <link href="static/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="static/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="static/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="static/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="static/css/tuck.css" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins">
        <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title">Doctor Registration</h2>
                    <form method="POST">
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="User Name" name="name">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="First Name" name="fname">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Last Name" name="lname">
                        </div>

                        <div class="input-group">
                            <input class="input--style-3 js-datepicker" type="text" placeholder="Birthdate" name="birthday">
                            <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                        </div>
                        <div class="input-group">
                            <div class="rs-select2 js-select-simple select--no-search">
                                <select name="gender">
                                    <option disabled="disabled" selected="selected">Gender</option>
                                    <option>Male</option>
                                    <option>Female</option>
                                    <option>Other</option>
                                </select>
                                <div class="select-dropdown"></div>
                            </div>
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="email" placeholder="Email" name="email">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Phone" name="phone">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Hospital Name" name="hname">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="file" placeholder="Profile Pic" accept="image/*" id="id_profile_pic">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="password" name="Password">
                        </div>





                        <div class="input-group">
                            <label class="rs-select2 js-select-simple select--no-search" for="id_specialities_type">Specialities
                                type:</label>
                            <select name="specialities_type" required id="id_specialities_type">
                                <option value=" " selected>Select field</option>
                                <option value="ENT ">Ear, Nose and Throat</option>
                                <option value="GS ">General Surgery</option>
                                <option value="OP ">Ophthalmology</option>
                                <option value="OR ">Orthopaedics</option>
                                <option value="OAG ">Obstetrics and Gynaecology</option>
                                <option value="DVL ">Dermatology, Venerology and Leprosy
                                </option>
                                <option value="AST ">Anaesthesiology</option>
                                <option value="PSY ">Psychiatry</option>
                                <option value="PTH ">Pathology</option>
                                <option value="SVD ">Skin and Venereal diseases</option>
                                <option value="PHRM ">Pharmacology</option>
                                <option value="PMR ">Physical Medicine and Rehabilitation
                                </option>
                                <option value="PHY ">Physiology</option>
                                <option value="CRD ">Cardiology</option>
                                <option value="PDT ">Paediatrics</option>
                            </select>
                            <div class="select-dropdown "></div>
                        </div>

                        <div class="p-t-10 ">
                            <button class="btn btn--pill btn--green " type="submit ">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="static/vendor/jquery/jquery.min.js "></script>
    <!-- Vendor JS-->
    <script src="static/vendor/select2/select2.min.js "></script>
    <script src="static/vendor/datepicker/moment.min.js "></script>
    <script src="static/vendor/datepicker/daterangepicker.js "></script>

    <!-- Main JS-->
    <script src="static/js/gg.js "></script>

</body>
<!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

templates/links.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Welcome to GHS</h1>

    {% if request.user.is_authenticated %}

    <a href="{% url 'test' %}">see here also</a> <br>
    <a href="{% url 'index' %}">just see</a> <br>
    <a href="{% url 'history' %}">History</a> <br>
    <a href="{% url 's' %}">s</a> <br>
    <a href="{% url 'book_appointment' %}">Book Appointment</a> <br>
    <a href="{% url 'show_appointment' %}">User Show Appointment</a> <br>
    <a href="{% url 'doctor_show_appointment' %}">Show Appointments (Doctor Side)</a> <br>

    <a href="{% url 'user_home' %}">User Home</a> <br>
    <a href="{% url 'doctor_home' %}">Doctor Home</a> <br>

    <a href="{% url 'signout' %}">Signout</a> <br> {% else %} <a href="{% url 'signup_user' %}">Signup User</a>

    <a href="{% url 'index' %}">Signup Doctor</a> <a href="{% url 'signin' %}">Signin</a> {% endif %}

</body>

</html>

<!-- 

    1 normal
    4 team
    2 features
    3 contact us
    5 

    For User
    Appointment booking
    History

    For Doctor
    History
    Appointment order

 -->

templates/signup_user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="icon" href="static/assets/img/Main_LOGO.png" type="image/x-icon">
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>User Registration</title>

    <!-- Icons font CSS-->
    <link href="../static/vendor2/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="../static/vendor2/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="../static/vendor2/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="../static/vendor2/datepicker/daterangepicker.css" rel="stylesheet" media="all">


    <!-- Main CSS-->
    <link href="../static/css/tutt.css" rel="stylesheet" media="all">

    <style>
        #id_gender {
            display: none;
        }
    </style>

    <style>
        body,
        html {
            width: 100%;
            height: 100%;
        }
        
        body {
            margin: 0;
            padding: 0;
            background: #000;
        }
        
        .bubbles {
            position: absolute;
            width: 100%;
            height: 100%;
            z-index: 0;
            overflow: hidden;
            top: 0;
            left: 0;
        }
        
        .bubble {
            position: absolute;
            bottom: -100px;
            width: 40px;
            height: 40px;
            background: #f1f1f1;
            border-radius: 50%;
            opacity: 0.5;
            animation: rise 10s infinite ease-in;
        }
        
        .bubble:nth-child(1) {
            width: 40px;
            height: 40px;
            left: 10%;
            animation-duration: 8s;
        }
        
        .bubble:nth-child(2) {
            width: 20px;
            height: 20px;
            left: 20%;
            animation-duration: 5s;
            animation-delay: 1s;
        }
        
        .bubble:nth-child(3) {
            width: 50px;
            height: 50px;
            left: 35%;
            animation-duration: 7s;
            animation-delay: 2s;
        }
        
        .bubble:nth-child(4) {
            width: 80px;
            height: 80px;
            left: 50%;
            animation-duration: 11s;
            animation-delay: 0s;
        }
        
        .bubble:nth-child(5) {
            width: 35px;
            height: 35px;
            left: 55%;
            animation-duration: 6s;
            animation-delay: 1s;
        }
        
        .bubble:nth-child(6) {
            width: 45px;
            height: 45px;
            left: 65%;
            animation-duration: 8s;
            animation-delay: 3s;
        }
        
        .bubble:nth-child(7) {
            width: 90px;
            height: 90px;
            left: 70%;
            animation-duration: 12s;
            animation-delay: 2s;
        }
        
        .bubble:nth-child(8) {
            width: 25px;
            height: 25px;
            left: 80%;
            animation-duration: 6s;
            animation-delay: 2s;
        }
        
        .bubble:nth-child(9) {
            width: 15px;
            height: 15px;
            left: 70%;
            animation-duration: 5s;
            animation-delay: 1s;
        }
        
        .bubble:nth-child(10) {
            width: 90px;
            height: 90px;
            left: 25%;
            animation-duration: 10s;
            animation-delay: 4s;
        }
        
        @keyframes rise {
            0% {
                bottom: -100px;
                transform: translateX(0);
            }
            50% {
                transform: translate(100px);
            }
            100% {
                bottom: 1080px;
                transform: translateX(-200px);
            }
        }
    </style>

</head>

<body>


    <section class="sticky">
        <div class="bubbles">
            <div class="bubble"></div>
            <div class="bubble"></div>
            <div class="bubble"></div>
            <div class="bubble"></div>
            <div class="bubble"></div>
            <div class="bubble"></div>
            <div class="bubble"></div>
            <div class="bubble"></div>
            <div class="bubble"></div>
            <div class="bubble"></div>

        </div>
    </section>

    {{user_form.errors}} {{user_info_form.errors}}

    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <h2 class="title">User Registration</h2>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">first name</label>
                                    <input class="input--style-4" type="text" name="first_name" maxlength="150" required id="id_first_name">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">last name</label>
                                    <input class="input--style-4" type="text" name="last_name" maxlength="150" required id="id_last_name">
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Date of birth</label>
                                    <div class="input-group-icon">
                                        <input class="input--style-4 js-datepicker" type="text" name="dob" maxlength="10" required id="id_dob">
                                        <i class=" zmdi zmdi-calendar-note input-icon js-btn-calendar "></i>
                                    </div>
                                </div>
                            </div>



                            <div class="col-2 ">
                                <div class="input-group ">
                                    <label class="label ">Gender</label>
                                    <div class="p-t-10 ">
                                        <label class="radio-container m-r-45">Male
                                            <input type="radio" name="gender" id="male">
                                            <span class="checkmark"></span>
                                        </label>
                                        <label class="radio-container ">Female
                                            <input type="radio" name="gender" id='female'>
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space ">
                            <div class="col-2 ">
                                <div class="input-group ">
                                    <label class="label ">Email</label>
                                    <input class="input--style-4 " type="email" name="email" maxlength="254" required id="id_email">
                                </div>
                            </div>
                            <div class=" col-2 ">
                                <div class="input-group ">
                                    <label class="label ">Phone Number</label>
                                    <input class="input--style-4 " name="mobile_number" maxlength="12" required id="id_mobile_number">
                                </div>
                            </div>
                        </div>
                        <div class="input-group ">
                            <div class="input-group">
                                <label class="label">Profile pic</label>
                                <input class="input--style-4" type="file" name="profile_pic" accept="image/*" required id="id_profile_pic">
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Username</label>
                                    <input class="input--style-4" type="text" name="username" maxlength="150" required id="id_username">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Password</label>
                                    <input class="input--style-4" type="password" name="password" minlength="8" required id="id_password">
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2" style="padding-left: 40px;">
                                <div class="input-group">
                                    <button class="btn btn--radius-2 btn--blue" type="reset">Reset</button>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <button onclick="funother()" class="btn btn--radius-2 btn--blue" type="submit" style="margin-left: 40px;">Register</button>
                                </div>
                            </div>
                        </div>

                        <select name="gender" required id="id_gender">
                            <option value="" selected>---------</option>

                            <option value="M">Male</option>

                            <option value="F">Female</option>
                        </select>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        function funother() {
            if (document.getElementById('male').checked) {
                document.getElementById(
                    "id_gender").selectedIndex = "1";
            } else {
                document.getElementById("id_gender").selectedIndex = "2";
            }
        }
    </script>

    <!-- Jquery JS-->
    <script src="../static/vendor2/jquery/jquery.min.js "></script>
    <!-- Vendor JS-->
    <script src="../static/vendor2/select2/select2.min.js "></script>
    <script src="../static/vendor2/datepicker/moment.min.js "></script>
    <script src="../static/vendor2/datepicker/daterangepicker.js "></script>

    <!-- Main JS-->
    <script src="../static/js/ttt.js "></script>
</body>


</html>
<!-- end document-->